# this will tell spring which yml file to pick for
# configuration

spring:
  profiles:
    active : dev
#  for multiples profile together, and configurations will be merged
#  this will require the handling of conflicts of keys and securityConfig files that
#  are based on profiles like @Profile("dev") or @Profile("prod")
#    active: dev, prod


#  common part here
#  configurations according to server environment
#  in that particular yml of the server and
  server:
    port: 8081
    servlet:
      context-path: /journal