spring.application.name=journalApp
server.port=8081
server.servlet.context-path=/abcd

#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#replce host and port with URI in case mongoDB Atlas - remote server db
# i have repalced @ as %40 in password as it had to be passed as url-encoded if contain : or @
spring.data.mongodb.uri=mongodb+srv://naveen-spring-user-mongo:naveen-mongo%406530@java-springboot.gytwyb7.mongodb.net/?retryWrites=true&w=majority&appName=Java-Springboot
spring.data.mongodb.database=journaldb

#configuration of mongodb to crete creation indexes automatically
spring.data.mongodb.auto-index-creation=true


#allowing circular depedency on code
spring.main.allow-circular-references = true

spring.security.user.name=naveen
spring.security.user.password=Admin@123