spring:
  data:
#    mongodb:
#      uri: mongodb+srv://naveen-spring-user-mongo:naveen-mongo%406530@java-springboot.gytwyb7.mongodb.net/?retryWrites=true&w=majority&appName=Java-Springboot
#      database: journaldb
#      auto-index-creation: true
  main:
    allow-circular-references: true
  application:
    name: journalApp
  security:
    user:
      name: naveen
      password: Admin@123

  #  configuration for mail sender, just like for mongotemplate, their beans
  #  are created by these configurations
  mail:
    host: smtp.gmail.com
    port: 587
    username: leisurenaveen@gmail.com
    #    password from app created on gmail using this email account
    password: rugq kkxh hntt sdch
    properties:
      mail:
        smtp:
          auth: true  #enabling authorization required
          starttls:
            enable: true  #data transfer between the server and email server is encrypted,  transport layer security

server:
  port: 3001
  servlet:
    context-path: /journal

weatherApiKey: 4867982c13ef2c83a6c9b0d26c3e343c

profile_key : "naveen-prod"
